export { default as Main } from "./main.jsx";
export { default as Hero } from "./components/Hero.jsx";
export { default as Onas } from "../onas/Onas.jsx";
export { default as NewsAndUseful } from "../newsAndUseFul/newsAndUseFul.jsx.jsx";
export { default as WeNews } from "../WeNews/WeNews.jsx";
export { default as Basket } from "../basket/Basket.jsx";
export { default as Catalog } from "../catalog/Catalog.jsx";
export { default as CatalogDetail } from "../CatalogDetail/CatalogDetail.jsx";
export { default as Contact } from "../contact/Contact.jsx";
export { default as Category } from "../category/Category.jsx";
// export { default as Login } from "../login/Login.jsx";
export { default as Product } from "../product/Product.jsx";
export { default as SubCategory } from "../subCategory/SubCategory.jsx";
export { default as NewsComp } from "../news/News.jsx";
export { default as EditProductImg } from "../editProductImg/editProductImg.jsx";
